import { Tender } from '../types';

export const initialTenders: Tender[] = [
  {
    id: 't-1',
    projectCode: 'PC-2026-NEOM',
    tenderNumber: 'TN-83921',
    projectName: { en: 'Neom Spine Ground Terminal Expansion', ar: 'توسعة محطة النفق الأرضية بمشروع نيوم' },
    location: { en: 'NEOM - Saudi Arabia', ar: 'نيوم - المملكة العربية السعودية' },
    coordinator: { en: 'Eng. Khalid Al-Saeed', ar: 'المهندس خالد السعيد' },
    contractsEngineer: { en: 'Ahmed Mostafa', ar: 'أحمد مصطفى' },
    tenderStudyEngineer: { en: 'Eng. Salem Al-Awadi', ar: 'المهندس سالم العوضي' },
    department: 'Pre-Award Civil Core',
    priority: 'Critical',
    techSubmissionDate: '2026-07-15',
    commSubmissionDate: '2026-08-01',
    overallSubmissionDate: '2026-08-15',
    closingDate: '2026-08-30',
    kickOffDate: '2026-06-15',
    alignmentDate: '2026-07-05',
    followUpDate: '2026-07-10',
    riskDueDate: '2026-06-24',
    contractQualsDueDate: '2026-07-01',
    projectStatus: { en: 'Ready for Submittal', ar: 'جاهز للتسليم' },
    awardStatus: { en: 'Under Negotiation', ar: 'تحت التفاوض' },
    recordStatus: 'Active',
    daysRemaining: 24,
    health: 'Healthy',
    estimatedValue: 'AED 430,200,000',
    estimatedCost: 'AED 412,000,000',
    bondAmount: 'AED 8,600,000',
    currency: 'AED',
    tenderType: { en: 'Design & Build', ar: 'تصميم وتشييد' },
    clientName: { en: 'NEOM Authority Co.', ar: 'شركة نيوم المساهمة' },
    consultant: { en: 'Dar Al-Handasah', ar: 'دار الهندسة المعتمدة' },
    branch: { en: 'Riyadh HQ', ar: 'الفرع الرئيسي الرياض' },
    businessUnit: { en: 'Infrastructure', ar: 'البنية التحتية' },
    notes: [
      { id: 'n1', author: 'Eng. Khalid Al-Saeed', date: '2026-06-20', text: 'All MEP clearances have been synchronized. Preparing final structural test results for enclosure.' },
      { id: 'n2', author: 'Ahmed Mostafa', date: '2026-06-18', text: 'Secured bulk rates override with local steel fabricators. Saving 4% on material budget margins.' }
    ],
    documents: [
      { id: 'd1', name: 'NEOMspine-DesignLayout-V4.pdf', size: '24.2 MB', link: '#' },
      { id: 'd2', name: 'IPC-CostEstimatesSheet-Final.xlsx', size: '12.4 MB', link: '#' },
      { id: 'd3', name: 'BankGuarantee-TenderDraft.pdf', size: '1.8 MB', link: '#' }
    ]
  },
  {
    id: 't-2',
    projectCode: 'PC-2026-DXB',
    tenderNumber: 'TN-47291',
    projectName: { en: 'Zayed Boulevard Commercial Corridor', ar: 'الممر التجاري الرئيسي بمحور الشيخ زايد' },
    location: { en: 'Dubai - United Arab Emirates', ar: 'دبي - الإمارات العربية المتحدة' },
    coordinator: { en: 'Eng. Sherif Amin', ar: 'المهندس شريف أمين' },
    contractsEngineer: { en: 'Khaled Hassan', ar: 'خالد حسن' },
    tenderStudyEngineer: { en: 'Eng. Omar Suleiman', ar: 'المهندس عمر سليمان' },
    department: 'Commercial Infrastructure',
    priority: 'High',
    techSubmissionDate: '2026-06-25',
    commSubmissionDate: '2026-07-01',
    overallSubmissionDate: '2026-07-10',
    closingDate: '2026-07-25',
    kickOffDate: '2026-05-26',
    alignmentDate: '2026-06-15',
    followUpDate: '2026-06-20',
    riskDueDate: '2026-06-04',
    contractQualsDueDate: '2026-06-11',
    projectStatus: { en: 'Preparing Proposal', ar: 'جاري إعداد العرض العلمي والمالي' },
    awardStatus: { en: 'Pending Selection', ar: 'في انتظار تحديد المقاول' },
    recordStatus: 'Active',
    daysRemaining: 4,
    health: 'Due Soon',
    estimatedValue: 'AED 620,000,000',
    estimatedCost: 'AED 595,200,000',
    bondAmount: 'AED 12,400,000',
    currency: 'AED',
    tenderType: { en: 'EPC Contract', ar: 'عقد هندسة وتشييد' },
    clientName: { en: 'EMAAR Properties', ar: 'إعمار العقارية' },
    consultant: { en: 'Parsons International', ar: 'بارسونز العالمية للاستشارات' },
    branch: { en: 'Dubai South', ar: 'فرع جنوب دبي font-ar' },
    businessUnit: { en: 'Real Estate Dev', ar: 'التطوير العقاري والمراكز' },
    notes: [
      { id: 'n3', author: 'Eng. Sherif Amin', date: '2026-06-19', text: 'Commercial proposal is awaiting executive board margin sign-off. Everything else compiles.' }
    ],
    documents: [
      { id: 'd4', name: 'DXB-Boulevardspecs-V2.pdf', size: '48.9 MB', link: '#' },
      { id: 'd5', name: 'Emaar-RFP-Addendum3.pdf', size: '4.1 MB', link: '#' }
    ]
  },
  {
    id: 't-3',
    projectCode: 'PC-2026-CAI',
    tenderNumber: 'TN-10294',
    projectName: { en: 'Cairo Capital East Logistics Hub', ar: 'المركز اللوجستي لشرق العاصمة الإدارية' },
    location: { en: 'New Cairo - Egypt', ar: 'القاهرة الجديدة - جمهورية مصر العربية' },
    coordinator: { en: 'Eng. Ramy Fawzy', ar: 'المهندس رامي فوزي font-ar' },
    contractsEngineer: { en: 'Fatma Amer', ar: 'فاطمة عامر' },
    tenderStudyEngineer: { en: 'Eng. Tamer Al-Gohary', ar: 'المهندس تامر الجوهري' },
    department: 'Logistics Projects',
    priority: 'Medium',
    techSubmissionDate: '2026-06-10',
    commSubmissionDate: '2026-06-15',
    overallSubmissionDate: '2026-06-20',
    closingDate: '2026-07-15',
    kickOffDate: '2026-05-11',
    alignmentDate: '2026-05-31',
    followUpDate: '2026-06-05',
    riskDueDate: '2026-05-20',
    contractQualsDueDate: '2026-05-27',
    projectStatus: { en: 'Submitted', ar: 'تم التسليم والمناقشة الفنية' },
    awardStatus: { en: 'Preferred Bidder', ar: 'المناقص المفضل الأفضل في الاستعراض' },
    recordStatus: 'Active',
    daysRemaining: -1,
    health: 'Overdue',
    estimatedValue: 'EGP 1,950,000,000',
    estimatedCost: 'EGP 1,870,000,000',
    bondAmount: 'EGP 39,000,000',
    currency: 'EGP',
    tenderType: { en: 'Design & Build', ar: 'تصميم وتشييد' },
    clientName: { en: 'Administrative Capital S.A.E', ar: 'شركة العاصمة الإدارية للتنمية العمرانية' },
    consultant: { en: 'ECG Engineering', ar: 'جماعة المهندسين الاستشاريين' },
    branch: { en: 'Cairo Branch', ar: 'فرع القاهرة' },
    businessUnit: { en: 'Commercial Hubs', ar: 'المراكز التجارية واللوجستيات' },
    notes: [
      { id: 'n4', author: 'Fatma Amer', date: '2026-06-12', text: 'Clarification query raised regarding foundation soil mechanics was resolved. Document attached.' }
    ],
    documents: [
      { id: 'd6', name: 'Cairo-EastLogistics-Proposal-Submitted.pdf', size: '18.3 MB', link: '#' }
    ]
  },
  {
    id: 't-4',
    projectCode: 'PC-2026-DIR',
    tenderNumber: 'TN-91827',
    projectName: { en: 'Diriyah Blvd District Substructure', ar: 'البنية التحتية لمنطقة بوليفارد الدرعية التاريخية' },
    location: { en: 'Riyadh - Saudi Arabia', ar: 'الرياض - المملكة العربية السعودية' },
    coordinator: { en: 'Eng. Yasmin Omar', ar: 'مهندسة ياسمين عمر' },
    contractsEngineer: { en: 'Salim Mansoor', ar: 'سليم منصور' },
    tenderStudyEngineer: { en: 'Eng. Hany Roushdy', ar: 'المهندس هاني رشدي' },
    department: 'Civil Understructure Unit',
    priority: 'Low',
    techSubmissionDate: '2026-05-30',
    commSubmissionDate: '2026-06-05',
    overallSubmissionDate: '2026-06-12',
    closingDate: '2026-06-30',
    kickOffDate: '2026-04-30',
    alignmentDate: '2026-05-20',
    followUpDate: '2026-05-25',
    riskDueDate: '2026-05-09',
    contractQualsDueDate: '2026-05-16',
    projectStatus: { en: 'Archived Submission', ar: 'ملف المزايدة مؤرشف' },
    awardStatus: { en: 'Completed', ar: 'انتهت المزايدة لصالح طرف آخر' },
    recordStatus: 'Archived',
    daysRemaining: 0,
    health: 'Archived',
    estimatedValue: 'SAR 310,000,000',
    estimatedCost: 'SAR 298,000,000',
    bondAmount: 'SAR 6,200,000',
    currency: 'SAR',
    tenderType: { en: 'Lump Sum Turnkey', ar: 'عقد تسليم مفتاح' },
    clientName: { en: 'Diriyah Gate Development Corp.', ar: 'هيئة تطوير بوابة الدرعية' },
    consultant: { en: 'Buro Happold', ar: 'بيورو هابولد للاستشارات' },
    branch: { en: 'Riyadh branch', ar: 'فرع الرياض' },
    businessUnit: { en: 'Infrastructure', ar: 'البنية التحتية والمرافق الإستراتيجية' },
    notes: [
      { id: 'n5', author: 'Eng. Yasmin Omar', date: '2026-05-15', text: 'Closed and archived as other priorities took over resource matrices internally.' }
    ],
    documents: [
      { id: 'd7', name: 'DiriyahDistrictSpecs_Standard.pdf', size: '9.4 MB', link: '#' }
    ]
  },
  {
    id: 't-5',
    projectCode: 'PC-2026-ALM',
    tenderNumber: 'TN-20938',
    projectName: { en: 'Al Maktoum Terminal Cargo Runway', ar: 'مدرج الشحن بمطار آل مكتوم الدولي الجديد' },
    location: { en: 'Dubai - United Arab Emirates', ar: 'دبي - الإمارات العربية المتحدة' },
    coordinator: { en: 'Eng. Khalid Al-Saeed', ar: 'المهندس خالد السعيد' },
    contractsEngineer: { en: 'Ahmed Mostafa', ar: 'أحمد مصطفى' },
    tenderStudyEngineer: { en: 'Eng. Kamal Al-Khatib', ar: 'المهندس كمال الخطيب' },
    department: 'Aviation Projects Division',
    priority: 'Critical',
    techSubmissionDate: '2026-08-20',
    commSubmissionDate: '2026-09-05',
    overallSubmissionDate: '2026-09-15',
    closingDate: '2026-10-15',
    kickOffDate: '2026-07-21',
    alignmentDate: '2026-08-10',
    followUpDate: '2026-08-15',
    riskDueDate: '2026-07-30',
    contractQualsDueDate: '2026-08-06',
    projectStatus: { en: 'Initial Stage', ar: 'المرحلة الأولية للمشروع' },
    awardStatus: { en: 'Pending Selection', ar: 'قيد انتظار الفتح الفني' },
    recordStatus: 'Active',
    daysRemaining: 60,
    health: 'Healthy',
    estimatedValue: 'AED 840,000,000',
    estimatedCost: 'AED 805,000,000',
    bondAmount: 'AED 16,800,000',
    currency: 'AED',
    tenderType: { en: 'EPC Contract', ar: 'عقد هندسة وتشييد' },
    clientName: { en: 'Dubai Aviation Engineering Projects', ar: 'دبي لمشاريع الطيران الهندسية' },
    consultant: { en: 'AECOM Middle East', ar: 'آيكوم الشرق الأوسط للاستشارات الهندسية' },
    branch: { en: 'Dubai HQ', ar: 'المكتب الرئيسي دبي' },
    businessUnit: { en: 'Heavy Civil', ar: 'المشاريع المدنية الثقيلة والمطارات' },
    notes: [
      { id: 'n6', author: 'Eng. Khalid Al-Saeed', date: '2026-06-20', text: 'Initial feasibility tests confirm that ground soil compact meets all runway specs. No premium sub-grade reinforcing is needed.' }
    ],
    documents: []
  },
  {
    id: 't-6',
    projectCode: 'PC-2026-NCW',
    tenderNumber: 'TN-55319',
    projectName: { en: 'New Cairo Wastewater Enclosure Ring', ar: 'الحلقة الدائرية لمحطة مياه القاهرة الجديدة font-ar' },
    location: { en: 'New Cairo - Egypt', ar: 'القاهرة الجديدة - جمهورية مصر العربية' },
    coordinator: { en: 'Eng. Yasmin Omar', ar: 'مهندسة ياسمين عمر' },
    contractsEngineer: { en: 'Sherif Amin', ar: 'المهندس شريف أمين' },
    tenderStudyEngineer: { en: 'Eng. Alaa El-Din', ar: 'المهندس علاء الدين' },
    department: 'Water & Wastewater Unit',
    priority: 'Medium',
    techSubmissionDate: '2026-06-29',
    commSubmissionDate: '2026-07-05',
    overallSubmissionDate: '2026-07-15',
    closingDate: '2026-08-15',
    kickOffDate: '2026-05-30',
    alignmentDate: '2026-06-19',
    followUpDate: '2026-06-24',
    riskDueDate: '2026-06-08',
    contractQualsDueDate: '2026-06-15',
    projectStatus: { en: 'Reviewing Scope', ar: 'جاري مراجعة نطاق العمل الفعلي' },
    awardStatus: { en: 'Under Negotiation', ar: 'قيد المراجعة والمطابقة' },
    recordStatus: 'Active',
    daysRemaining: 7,
    health: 'Due Soon',
    estimatedValue: 'EGP 980,000,000',
    estimatedCost: 'EGP 940,000,000',
    bondAmount: 'EGP 19,600,000',
    currency: 'EGP',
    tenderType: { en: 'Design & Build', ar: 'تصميم وتشييد' },
    clientName: { en: 'Ministry of Housing, Utilities S.A.', ar: 'وزارة الإسكان والمرافق العمرانية' },
    consultant: { en: 'Sabbour Consulting', ar: 'صَبور للاستشارات الهندسية' },
    branch: { en: 'Cairo Branch', ar: 'فرع القاهرة الكبرى' },
    businessUnit: { en: 'Heavy Civil', ar: 'المشروعات المدنية الكبرى والمياه' },
    notes: [
      { id: 'n7', author: 'Eng. Yasmin Omar', date: '2026-06-17', text: 'Shared preliminary steel pricing with estimating engine to update structural parameters.' }
    ],
    documents: [
      { id: 'd8', name: 'RingWastewaterSpecifications-V1.pdf', size: '14.0 MB', link: '#' }
    ]
  }
];
